blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/plac9/afk-journey-hub/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/plac9/afk-journey-hub/tree/main/docs
    about: Check the documentation for guides and references
  - name: AFK Journey Official Support
    url: https://afkjourney.farlightgames.com/official/
    about: For game-specific issues, contact official support
